[functions.get-session-element]
enabled = true
verify_jwt = true
import_map = "./functions/get-session-element/deno.json"
entrypoint = "./functions/get-session-element/index.ts"

[functions.start-new-session]
enabled = true
verify_jwt = true
import_map = "./functions/start-new-session/deno.json"
entrypoint = "./functions/start-new-session/index.ts"