[functions.get-session-element]
enabled = true
verify_jwt = true
import_map = "./functions/get-session-element/deno.json"
entrypoint = "./functions/get-session-element/index.ts"

[functions.start-new-session]
enabled = true
verify_jwt = true
import_map = "./functions/start-new-session/deno.json"
entrypoint = "./functions/start-new-session/index.ts"
[functions.grade-frq]
enabled = true
verify_jwt = true
import_map = "./functions/grade-frq/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/grade-frq/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/grade-frq/*.html" ]

[functions.process-paddle-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/process-paddle-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-paddle-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-paddle-webhook/*.html" ]

[functions.update-cache]
enabled = true
verify_jwt = true
import_map = "./functions/update-cache/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-cache/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-cache/*.html" ]
